# kubectl create token logrotate --duration 876000h | gh secret set K8S_TOKEN
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logrotate
  namespace: prod-core-vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logrotate
  namespace: prod-core-vault
rules:
- apiGroups: [""]
  resources: ["pods/exec", "pods"]
  verbs: ["create", "get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logrotate
  namespace: prod-core-vault
subjects:
- kind: ServiceAccount
  name: logrotate
  namespace: prod-core-vault
roleRef:
  kind: Role
  name: logrotate
  apiGroup: rbac.authorization.k8s.io
